// js/state.js
// Single source of truth for "where the user is" in the app, plus the
// tiny router (nav/back/render) that every page and card uses.
// Pages never touch the DOM directly except through these helpers.

export const S = {
  authed: false,
  page: 'login',
  stack: [],
  activityTab: 'ongoing',
  currentProvider: null,
  currentTask: null,
  currentChat: null,
  requestDraft: { name: '', location: '', feeMin: '', feeMax: '', note: '' },
  pendingEmail: '',
  marketQuery: '',
};

let routes = {};

// Called once from app.js after every page module has been imported.
export function registerRoutes(routeMap) {
  routes = routeMap;
}

export function render() {
  const fn = routes[S.page] || routes.login;
  document.getElementById('view').innerHTML = fn();
}

// Navigate to a page. Pushes the current page onto the back-stack unless
// { push:false } is passed (used by bottom-nav taps, which reset history).
export function nav(page, opts = {}) {
  if (opts.push !== false) S.stack.push(S.page);
  if (opts.reset) S.stack = [];
  S.page = page;
  render();
  const view = document.getElementById('view');
  if (view) view.scrollTop = 0;
}

export function back(fallback = 'home') {
  S.page = S.stack.pop() || fallback;
  render();
}

export function toast(msg) {
  const t = document.getElementById('toast');
  if (!t) return;
  t.textContent = msg;
  t.classList.add('show');
  clearTimeout(toast._h);
  toast._h = setTimeout(() => t.classList.remove('show'), 2200);
}

// Expose the navigation primitives globally so inline onclick="nav('home')"
// strings generated by page templates can call them directly.
window.nav = nav;
window.back = back;
window.toast = toast;
