project_id = "tasktify-main-app"

[functions.tasks]
verify_jwt = true

[auth]
site_url = "https://www.tasktify.id"
additional_redirect_urls = [
  "https://tasktify.id/auth/callback",
  "https://www.tasktify.id/auth/callback",
  "http://localhost:3000/auth/callback",
]

[auth.email.template.confirmation]
subject = "Konfirmasi akun Tasktify Anda"
content_path = "./supabase/templates/confirmation.html"
